### ISSUE TITLE
一些小问题

### ISSUE THREAD

**Issue by kanamomono** [fangfang1122/ToDoList-wechatApp#2]
大佬您好，很佩服您能做出这样一个精美的小程序，本人因为太菜了有一些问题想向您请教。我把您的源代码放进微信小程序开发工具里面可以运行但是一直提示我”保存失败“”获取失败“”请打开小程序进行登录“等等问题，我看您发布了一个前端一个后端，我不太了解，请问是要配置一下后端吗，请问该如何解决，如果能得到您的指点将感激不尽！祝您生活顺利，学业有成！

**Comment by funcfang** [comment]
> 大佬您好，很佩服您能做出这样一个精美的小程序，本人因为太菜了有一些问题想向您请教。我把您的源代码放进微信小程序开发工具里面可以运行但是一直提示我”保存失败“”获取失败“”请打开小程序进行登录“等等问题，我看您发布了一个前端一个后端，我不太了解，请问是要配置一下后端吗，请问该如何解决，如果能得到您的指点将感激不尽！祝您生活顺利，学业有成！

hi你好~我刚刚简单看了下，不好意思，是我这边服务器的问题，目前服务器的ip我绑定到我另一个域名上面了，所以之前的todolist.cn域名访问会出现SSL证书失效，导致微信小程序这边会发不出请求。现在已经修复好了，你拉取最新代码就行。

或者你不拉取代码还有其他方法：
1.  微信开发者工具 - 详情 - 不校验合法域名。
2.  你尝试参考我的后端代码部署你自己的后端服务。

希望能帮助到你。
